name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'   # runs automatically when you push a version tag like v0.1.0
  workflow_dispatch:   # allows manual trigger from GitHub UI
    inputs:
      version:
        description: 'Package version (overrides .csproj if provided)'
        required: false
        default: ''

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: |
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            dotnet pack --configuration Release --no-build -o ./nupkgs /p:Version=${{ github.event.inputs.version }}
          else
            dotnet pack --configuration Release --no-build -o ./nupkgs
          fi

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./nupkgs/*.nupkg" --source "https://nuget.pkg.github.com/neurophex/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
