name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'   # e.g. v0.1.0 → only publish when you tag a release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # required to publish to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build -o ./nupkgs

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./nupkgs/*.nupkg" \
               --source "https://nuget.pkg.github.com/neurophex/index.json" \
               --api-key ${{ secrets.GITHUB_TOKEN }}